Rel/rec 4.6.x (#1)
* dnsdist: Don't copy the header twice when editing the ID

As suggested by Otto.

* dnsdist: Make ConnectionToBackend::release() purely virtual

* dnsdist: Also allocate buffers and connect sockets for CLI backends

* Some things you should do when handling untrusted zone files.

* dnsdist: Do not try to reconnect UDP sockets for TCP-only backends

* wipe-cache-typed  should check if a qtype arg is present and valid

* dnsdist: Handle existing EDNS content for SetMacAddrAction/SetEDNSOptionAction

* A SHA-384 DS should not trump a SHA-256 one, so only potentially zap SHA-1

* Reformat a bunch of recursor specific files

* dnsdist: Remove the useless step parameter in TCP and HTTP/2 unit tests

As suggested by Otto.

* Fix a linking issue with GCC 11.1.0

* dnsdist: Fix build without nghttp2

* dnsdist: Add the ability to retain select capabilities at runtime

* Fix regression of carbon-ourname introduced in 58d7ad6bfb0d46b7617ca984b90feacae35752c8
Noted by @mnordhoff

* dnsdist: Reply with NODATA for non-SVC types in the SVC documentation

* Carbon regression test for rec and auth.

Copied from dnsdist one. That test uses two difference instance names, but
rec and auth settings do not allow that.

* dnsdist: Only update 'ednsAdded' and 'optionAdded' if we process the query

* Move to a stream based socket for the control channel

* Use FDWrapper

* Do not read further than the length we received, the string might
be followed by a passed fd.

Interesting to see that OpenBSD chops up recvs based on the sends,
while Linux is happy to read more than was passed to the corresponding
send call if another send was called after that.

* Update security.rst

* Update security.rst

* Remove debug print line flooding logs

Remove debug log line printing a statement into stdout all the time.

* Initial stab at running the recursor regress and bulk tests on GH workflows

Some issues had to be worked around: libfaketime and bulk test network load

* Reduce size of bulk test and run it using a matrix to vary settings

* Separate bulk test deps from regression test deps

* Rename bulk test to make it clear it is mini

* Prep for rec-4.4.7 and rec-4.5.7

* dnsdist: Add 'InCsumErrors' UDP metric

* rec: Add 'InCsumErrors' UDP metric

* auth: Add 'InCsumErrors' UDP metric

* dnsdist: Add IPv6 UDP error metrics

* dnsdist: Fix dumpStats() formatting

* auth: Add IPv6 UDP error metrics

* rec: Add IPv6 UDP error metrics

* dnsdist: Document new UDP error metrics

* Add 'csum' to the list of allowed words (SNMP checksum metrics)

* Remove tabs in misc.cc

* dnsdist: Remove one last forgotten boost::bind in dnsdist.hh

* Remove dnsdist specific tests that remained

* Credentials: EVP_PKEY_CTX_set1_scrypt_salt() takes an `unsigned char*`

* auth: pdns_control needs to be linked against libcrypto now

* dnsdist: Disable 'IncludeDir' tests on GH actions

* Update dnsdist.cc

* cast arg of EVP_PKEY_CTX_set1_pbe_pass() to const void * to satisfy both openssl 1.1 and 3.0

* auth, rec: put some json on /api/v1

* remove a bunch of unnecessary &

* Reformat

* Update pdns/dnsdist.cc

Co-authored-by: Remi Gacogne <github@coredump.fr>

* some updates to CONTRIBUTING.md

* If possible, use SuffixMatchNodeRule() instead of RegexRule

* Update CONTRIBUTING.md

Co-authored-by: Otto Moerbeek <otto.moerbeek@open-xchange.com>

* better docblock note

* namespace

* auth: improve SOA dnsname exception handling

* Fix quad9 example servers that had run together

* dnsdist: Remove unreachable code in HTTP/2 connections cleanup

Reported by Coverity (CID 373724).

* dnsdist: Fix missing 'continue's when cleaning the connections cleaning code

* dnsdist: Refactoring of the TCP connection caches

* dnsdist: Fix a race condition in the XFR regression tests

* dnsdist: Add a unit test for the outgoing connection cache

* dnsdist: Fix formatting of the connections cache unit tests

* dnsdist: Split the list of downstream connections in two, active and idle

This way we can easily keep track of how many idle connections we have,
and try to reuse these first.

* dnsdist: Test that reused connections are moved to the active queue

* dnsdist: Formatting...

* auth: api, check qtype location. Some types only live apex and some are not allowed (or useful) there.

* auth: check domain_id in the info-all-master-query

* auth: api, remove CDS and CDNSKEY for now, in favor of https://www.ietf.org/archive/id/draft-thomassen-dnsop-dnssec-bootstrapping-02.html

* Review remarks from Habbie

* auth: make the zonecache more robust for bad data and save some SOA queries
for dnssec zones

* Use a global timeout for the various recv's we're doing to get a control message

* Limit max arg length

* Use sysconf if needed to get ARG_MAX

* Prep for rec-4.6.0-beta1

* Correct versionadded

* Fix formatting for versionadded

* auth bindbackend: skip rejected zones during list and search, fixes #10885

* stop saying mysql is a good choice for performance

* improve chroot text

* auth-4.5.2: secpoll and changelog

* We need libcurl dev lib for the zone-to-cache function.

Also fix config summary line and print curl feature on --version

* Clarify docs

* Move asan plus ubsan settings to strategy, in preparation for also doing tsan

* Remove other remains of GnuTLS config that was never useful

* Enable tsan build plus tests for rec GH actions

* Run fewer CircleCI bulk tests. These are covered by builbot anyway

* Supress g_stats data races

* Disable bulk test with TSAN for now and add some debug code to api test

* print stderr and stdout for api test

* rec: Allow worker threads to send tasks to handler thread

Extend the ThreadMSG mechanism to allow worker threads to submit
tasks to be executed by the handler thread (one-way only, no
answers can be returned).

* rec: Refactor cache-wiping code into a common function

Eliminates multiple copies of the code and eliminates
inconsistencies between them.

* rec: Add support for NOTIFY operations to wipe cache entries

NOTIFY operations can be sent to trigger removal of cache entries which
match the zone specified in the operation. All entries, regardless of
type, in or below the specified zone, are removed.  Control over
permission to send such operations is provided by an ACL, and control over
zones which can be wiped is provided by a new configuration setting.

The default configuration ignores all NOTIFY operations.

This patch adds:

* 'allow-notify-from' and 'allow-notify-from-file' settings, operating
  almost identically to 'allow-from' and 'allow-from-file' (the only
  difference being the default value).

* 'allow-notify-for' and 'allow-notify-for-file' settings, which provide
  a list of zones for which NOTIFY operations are allowed.

* modification to 'forward-zones-file' setting, allowing zones specified
  there to optionally allow NOTIFY operations.

* 'source-disallowed-notify' metric, counting the number of NOTIFY operations
  which have been denied by the ACL.

* 'zone-disallowed-notify' metric, counting the number of NOTIFY operations
  which have been denied by the zone list.

* API support for modifying 'allow-notify-from' ACL.

* Regression tests for new ACL settings.

* Disable the actual connect() in the test_dnsdisttcp_cc_c unit tests.

They are not needed and cause (at least on OpenBSD) firewall state table
clashes: they remain in a embryotic state because no actual activity
occurs on them due to the rest of the tests using mockup code.

tcpiohandler.cc is not linked into the tests, so define it locally in
test-dnsdisttcp_cc.cc as well.

* Update pdns/recursordist/RECURSOR-MIB.txt

Co-authored-by: Otto Moerbeek <otto.moerbeek@open-xchange.com>

* Return the proper ede on validation failure; fixes #10936

* dnsdist: Apply suggestions from code review (thanks, Otto!)

* Add test

* Add a test for ede sig expired that does not rely on external servers

* some more ()'s for readability

Co-authored-by: Remi Gacogne <github@coredump.fr>

* More strict secpoll check; hope I got the yaml quoting right

* Move check to a shell script

* tweaks and undo error entry

* no else after exit

Co-authored-by: Josh Soref <2119212+jsoref@users.noreply.github.com>

* auth 2136: improve some log messages

* auth 2136: apply new TTL to whole RRset, not only to the added record

fixes #10921

* indent

* dnsdist: Implement filesystem pinning for eBPF maps

This makes the filter (v4, v6 and qnames) maps persistent across a
restart and allow external programs to read and update them without
the need to use dnsdist's console.

* dnsdist: Add a new eBPF map format, support external eBPF programs

Supporting external eBPF programs makes it possible to populate the
eBPF tables from dnsdist, manually or via our dynamic blocking mechanisms,
but to actually do the filtering in an external program, like an XDP one.

We cannot increase the size of eBPF programs if we want to stay
below 4k instructions for older kernels, so this commit implements
a compatibility layer with the new map format.

The 4k limit for unprivileged was removed in 5.2 but the complexity limit remains:
The complexity limit was actually changed several times since the
32k value from its introduction in Linux 3.18: it was raised to 64k
in Linux 4.7, then to 96k in Linux 4.12, again to 128k in Linux 4.14,
and at last to 1M in Linux 5.2.

* dnsdist: Add a sample XDP program and associated python script in contrib

Both contributed by Pierre Grié <pierre.grie@nameshield.net>.

* contrib/xdp.py: Apply the change suggested by Pieter (thanks!)

Co-authored-by: Pieter Lexis <pieter@plexis.eu>

* dnsdist: Apply suggestions from code review on the new eBPF map type

* dnsdist: Switch to a uint8_t for the XDP match action type

* dnsdist: Add ChangeLog and secpoll update for 1.7.0-beta1

* spellcheck: Allow 'XDP', 'Grié'

* dnsdist: Fix the description of 10920 in the ChangeLog, remove useless entries

* Basic notify test.

It turns out a notify increments cache-hits, that feel a bit strange.

(cherry picked from commit 8662d268897b8b82145f4642dbb2a59f049a663a)

* Do not count notifies in record cache hits/misses

(cherry picked from commit 0fd8cf215c84b814f86673d58ed12142e0c36f0f)

* Positive instead of negative test

Co-authored-by: Pieter Lexis <pieter@plexis.eu>
(cherry picked from commit 5a642e0b648b22f884bbd0b517c431eb90e6b9e0)

* Include sys/time.h; needed on musl; fixes #11000

(cherry picked from commit 671ca0dee0cb529856af414e5b00db1b8b1e4d95)

* Fix logic botch introduced by notify handing

See #10751, some extra scrutiny review is needed to make sure no
other similat issue remains.

(cherry picked from commit 09a22e8c919b2ed55d98723fb14a33948aa6f517)

* When we drop a notify over TCP, terminate the connection

(cherry picked from commit 9aa6eeca355c50bc79e9f7ea986689fa0a296e42)

* Do cache negcache results, even when wasVariable() is true

See https://datatracker.ietf.org/doc/html/rfc7871#section-7.4
Fixes #10994

(cherry picked from commit 2bcec14adbffbf4b28d698cb607877fb96054e87)

* Condition to HAVE_SYSTEMD_WITH_RUNTIME_DIR_ENV is reversed

(cherry picked from commit fc1f6fb803e3ab7346f327b6113fc79eaa40abf2)

* Disable tsan regression runs for rec for now, there is a failure
mode that if it hits makes almost all remaining test fail.  Symptom
is that the auths do not start up properly.

(cherry picked from commit 2ef0d14bf39fafa45d39d5a0b5e8e5f263357d17)

* Fix v6 setup and start using a more modern auth on circleci

(cherry picked from commit 2d0fc474f8b03b536a95c6b9b05e96c6e8c51e30)

* One more occurence of --local-ipv6

(cherry picked from commit 9b3fc866b7f8133d4317aec9253e4b5fb0a385f9)

* Fix error in test zone that auth-45 does not like

(cherry picked from commit f1f41a8aa9299a4d8bf369c4fc0cb611f5b979cd)

* Do not generate eventtrace records if no Lua hook is defined

(cherry picked from commit 6a948130b2406d0e3b295ec68f56b3b8ed302960)

* Remove capability requirements from Docker images

(cherry picked from commit f28c81ed0242b6838eafdb61933a6f63b68040cf)

* Additional note on Docker Engine version where the requirement of the additional capability was dropped

(cherry picked from commit 07b24e5743c08c828c73a93e724a86a5b83b680a)

* Two more features to print

(cherry picked from commit 030c37636cea0dd449acdc9d14f03b2e27ad0791)

* Try shorter thread names

https://man7.org/linux/man-pages/man3/pthread_setname_np.3.html

       ... The thread name is a
       meaningful C language string, whose length is restricted to 16
       characters, including the terminating null byte ('\0').

(cherry picked from commit f3813e097ef9b4053009372e8009915bcd496a63)

* Make trySetThreadName static

Co-authored-by: Otto Moerbeek <otto.moerbeek@open-xchange.com>
(cherry picked from commit 80f15f6437c5a01c09d8f64cf252b68f6a77a083)

* rec-4.6.x: Fix build with OpenSSL 3.0.0

(cherry picked from commit 8535f66672ec9d1eebf5835d3e53238973a80478)

* CI: dnspython 2.2.0 breaks auth and ixfrdist testing, pin to 2.1.0

(cherry picked from commit 46a40ed033d64f58aa30013d7e68daa5b5e8d615)

* servfail.nl changed theuir setup.

I think in an ideal world we should return 9 (DNSSEC key missing) but I don't see a
easy way to do that at the moment.

(cherry picked from commit 2cd34ba5c565ee6bad368f577e34fa6d9519ab7d)

* stop testing auth+dnsdist on rec branch

* builder: archs for oraclelinux-8; el-8 symlinks

(cherry picked from commit dee53cf16161a6c45560475b647de420842532ef)

* builder CI: switch oraclelinux-8 to el-8

cleanup

(cherry picked from commit 1b27721782ad3dc547ed448a257c59829ff0bd94)

* take centos 8-stream from quay

(cherry picked from commit 2f9edddc0c9c1f8a68e154f6c12e3fd214420563)

* builder: add el-7 alias for centos-7

(cherry picked from commit 6bd3c9bb23f5dfc385a66647ab175ec2812d6617)

* add ubuntu jammy build target

(cherry picked from commit 6c1e5fd70b4dd4e75b18ff8c75f93c7d22122643)

* test ubuntu jammy build target

(cherry picked from commit e3d50799180eb4499f8dda5263773775301bfa7e)

* rec: Reject non-apex NSEC(3)s that have both the NS and SOA bits set

Ancestor NSEC(3)s have the SOA bit clear (delegation), and the remaining
non-apex ones should not have the NS set.

(cherry picked from commit be5d851dbedeecdeef39a583f0e2ac50d786b806)

* rec: The NSEC3 ancestor check must be done against the original owner name

(cherry picked from commit f37a904f4cc53ccb74b5904948b819920401ed24)

* NSEC -> NSEC3

Co-authored-by: Otto Moerbeek <otto.moerbeek@open-xchange.com>
(cherry picked from commit 78cee42937e5265bf6e0d5c1dc1fdaf684932a5a)

* NSEC -> NSEC3

Co-authored-by: Otto Moerbeek <otto.moerbeek@open-xchange.com>
(cherry picked from commit c67b13a9aa2c8c4092de28c1bb37e8bbb32dcee3)

* If we get a CNAME when asking for a DS, we should give up and return vState::BogusUnableToGetDSs

(cherry picked from commit 271ae639803453a6193b6c3c2baf034446a9965a)

* Add a test for the case where an (Insecure) domain fails to get a DS
record because of a CNAME loop, avoiding a SERVFAIL.

(cherry picked from commit c10acee8f241f7fa038fb5904d4bf71124093ac4)

* Fix indent

(cherry picked from commit 5db4dcaa91deeb3dbb0ebfbec828e7d224eca074)

* Initialize isNew before calling a exception throwing function

(cherry picked from commit 4043238ede86eb42dad0bd4eae0b51cb351e80ab)

* Allow disabling of processing the root hints

This also make sure we use the right dnssec mode for processing hints
and changes a few log levels to Debug to be less verbose.

(cherry picked from commit e46b0f2f7f4f20f92190a9202a7823ffe2123d98)

* Upgrade guide and doc tweaks

(cherry picked from commit 067a807cbc008d2b4c79a3ebe709226d46ff7718)

* Log an error if pdns.DROP is used as rcode in Lua callbacks

(cherry picked from commit f3f042efd2a1aff444f18e7d9e23ffc631b1b36f)

* Apply suggestions from code review

Co-authored-by: Remi Gacogne <github@coredump.fr>
(cherry picked from commit f7c973de073a5cae0af462cb86285eedcc76fd01)

* If we get NODATA on an AAAA in followCNAMERecords, try dns64

Fixes #11320

(cherry picked from commit aa59465e46b6fd617bf992a80da400ae14fbb4ec)

* Add test case for #11320:  followCNAMERecords leads to a result that
should be subject to dns64 processing

(cherry picked from commit 63ad9c90eb8f1842d2d79acefa803db9f820e33d)

* QType ADDR is supposed to be used internally only.

Should fix #11337

(cherry picked from commit 7a278799ee23e582c3b722cea578699db1791bc2)

* Backport of 11300 to rec-4.6.x: Use the Lua context stored in SyncRes when calling hooks

* Be more careful using refresh mode only for the record asked.
Otherwise we get bad interaction with QM, as newly discovered
delegation points are stored in the cache, but not seen the QM
algorithm. Might/should fix #11371.

(cherry picked from commit 7502f5f3b9293bed2601be2c479780f94438b45b)

* Reinstate refresh mode for {C,D}NAME cache lookups

(cherry picked from commit 3263b3adf19081274a9e36891eb202d75685ecfa)

* auth, rec IXFR-in: Fix a case where an incomplete read caused by network error might result in a truncated zone.

As we might break from the loop early, we need to check if the end SOA was seen after the loop.
Also make sure we detect end conditions for both AXFR and IXFR style properly, to avoid processing
data after the end marker.

* CI: dnspython 2.2.0 breaks auth and ixfrdist testing, pin to 2.1.0

(cherry picked from commit 46a40ed033d64f58aa30013d7e68daa5b5e8d615)

* stop testing auth+dnsdist on rec branch

* builder: archs for oraclelinux-8; el-8 symlinks

(cherry picked from commit dee53cf16161a6c45560475b647de420842532ef)

* builder CI: switch oraclelinux-8 to el-8

cleanup

(cherry picked from commit 1b27721782ad3dc547ed448a257c59829ff0bd94)

* take centos 8-stream from quay

(cherry picked from commit 2f9edddc0c9c1f8a68e154f6c12e3fd214420563)

* builder: add el-7 alias for centos-7

(cherry picked from commit 6bd3c9bb23f5dfc385a66647ab175ec2812d6617)

* rec: Fix the path to the recursor's UBSan suppression file in forks

* docs: Pin jinja2 to < 3.1.0

Jinja2 3.1.0 removed deprecated code that is still used by sphinx
1.8.x, and it looks like our custom sphinx extensions are not working
with more recent versions of sphinx..

See:
- https://github.com/pallets/jinja/issues/1631
- https://github.com/readthedocs/readthedocs.org/issues/9037

and

- https://github.com/PowerDNS/pdns/pull/7712

The exact error is:
```
Extension error:
Could not import extension sphinx.builders.latex (exception: cannot import name 'contextfunction' from 'jinja2' (/dnsdist/pdns/dnsdistdist/.venv/lib/python3.7/site-packages/jinja2/__init__.py))
```

(cherry picked from commit 92ad29702011ac7cbd0d7d118ba612e7e07cedbe)

* 4.6.x has no waitForTCPSocket plus counts are different due to rpz loading changes in master

* rec: Backport of 11496 to rec-4.6.x: Prevent segfault with empty allow-from-file and allow-from options

Co-authored-by: Remi Gacogne <remi.gacogne@powerdns.com>
Co-authored-by: Otto <otto.moerbeek@open-xchange.com>
Co-authored-by: Eugen Mayer <136934+EugenMayer@users.noreply.github.com>
Co-authored-by: Peter van Dijk <peter.van.dijk@powerdns.com>
Co-authored-by: phonedph1 <20867105+phonedph1@users.noreply.github.com>
Co-authored-by: Pieter Lexis <pieter.lexis@powerdns.com>
Co-authored-by: Remi Gacogne <github@coredump.fr>
Co-authored-by: Kees Monshouwer <mind04@monshouwer.org>
Co-authored-by: Nivex <nivex@nivex.net>
Co-authored-by: Frank Louwers <frank@louwers.be>
Co-authored-by: Kevin P. Fleming <kevin@km6g.us>
Co-authored-by: Kevin P. Fleming <kpfleming@users.noreply.github.com>
Co-authored-by: Otto Moerbeek <otto@pepper.intra.drijf.net>
Co-authored-by: Josh Soref <2119212+jsoref@users.noreply.github.com>
Co-authored-by: Remi Gacogne <rgacogne+github@valombre.net>
Co-authored-by: Pieter Lexis <pieter@plexis.eu>
Co-authored-by: Nico Vaatstra <nico.vaatstra@open-xchange.com>
Co-authored-by: Josh Soref <jsoref@users.noreply.github.com>